apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: practice
spec:
  containers:
  - args:
    - nginx-request
    image: nginx
    name: pod
    resources:
      requests:
        cpu: "100m"
        memory: "256mi"
      limits:
        cpu: "200m"
        memory: "512mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
