apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: default-mem-check
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
