apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-db
spec:
  replicas: 3
  serviceName: db-service
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      name: db-pod
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - name: db-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      storageClassName: db-storageclass
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi