apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a configmap Index file! \n HOSTNAME: $HOSTNAME</h1>
    </html
