apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp
  namespace: webns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      labels:
        name: webserver
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      nodeSelector:
        system: webapplication
