apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - image: nginx
    name: webserver
    resources: {}
    volumeMounts:
    - name: nginxconfig
      mountPath: /usr/share/nginx/index.html
  volumes:
  - name: nginxconfig
    configMap:
      name: nginxconfig
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
